from pathlib import Path

# 获取当前项目根目录 E:\code\ai_review
ROOT_PATH = Path(__file__).parents[1]
DATA_PATH = ROOT_PATH / 'data'
LOG_PATH = ROOT_PATH / 'log'
MODEL_PATH = ROOT_PATH / 'model'

BATCH_SIZE = 64

EPOCH=1
STEP_SIZE = 200
LR = 1e-5
WARMUP_STEPS=100
WEIGHT_DECAY=0.01
GRADIENT_ACCUMULATION_STEPS=2
REPORT_TO='tensorboard'
LOGGING_STEPS=32
EVAL_STRATEGY='steps'
EVAL_STEPS=100
PER_DEVICE_EVAL_BATCH_SIZE=256
LOAD_BEST_MODEL_AT_END=True
SAVE_STEPS=100

if __name__ == "__main__":
    print(ROOT_PATH)
